# Makefile
#
# Copyright (C) 2017, Makesystem, Balamurugan Souppourayen
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#

include ../../makesystem/COMMON_BIN_TARGET.mk


